name: Compile Arduino Sketch

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  compile:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Arduino CLI
      - name: Set up Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install the required Arduino core (e.g., Arduino AVR)
      - name: Install Arduino AVR core
        run: |
          arduino-cli core install arduino:avr

      - name: Install required libraries
        run: |
          arduino-cli lib install "Adafruit_Sensor"

      # Compile the sketch
      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn rduino:avr:nano:cpu=atmega328 ./Arduino/SQM_nano/SQM_nano.ino

      # Upload the compiled .hex file as an artifact
      - name: Upload .hex file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: ./Arduino/Firmware/*.hex