name: Compile Arduino Sketch

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  compile:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:avr:nano:cpu=atmega328"
          platforms: |
            - name: arduino:samd
          libraries: |
            - name: Adafruit Sensor
          sketch-paths: |
            - Arduino/SQM_nano